// Generated by PartnerHub PH-005B. Do not edit manually.
const CONFIG = {
  "site": {
    "id": "dorian-higuita",
    "domain": "dorianhiguita.pro",
    "title": "DorianWellness â€” Bienestar y Vitalidad con Gano Excel",
    "appName": "dorian_higuita",
    "ogTitle": "DorianWellness â€” Bienestar y Vitalidad con Gano Excel",
    "ogDescription": "Descubre como transformar tu dia a dia con cafe, cacao y suplementos enriquecidos con Ganoderma lucidum por DorianWellness.",
    "metaDescription": "Descubre como transformar tu dia a dia con cafe, cacao y suplementos enriquecidos con Ganoderma lucidum por DorianWellness."
  },
  "distributor": {
    "brandName": "DorianWellness",
    "firstName": "Dorian",
    "fullName": "Dorian Higuita",
    "role": "Distribuidor Autorizado Â· Gano Excel",
    "whatsappNumber": "3132794180",
    "phoneNumber": "3216628760",
    "displayPhone": "3216628760",
    "purchaseUrl": "https://col.ganoexcel.com/dorianwellness",
    "defaultMessage": "Hola Dorian, vengo de tu pÃ¡gina web. Me gustarÃ­a tener mÃ¡s informaciÃ³n sobre el Ganoderma de Gano Excel."
  },
  "hero": {
    "desktop": "https://media.partnerhub.club/clientes/dorian-higuita/producto/v1/hero-desktop-ms7vnbfs.webp",
    "mobile": "https://media.partnerhub.club/clientes/dorian-higuita/producto/v1/hero-mobile-ms7vndsa.webp"
  },
  "mediaBaseUrl": "https://media.partnerhub.club/comunes/producto/v1/"
};

if (typeof window !== "undefined") {
  window.CONFIG = CONFIG;
}
