$ErrorActionPreference = "Stop"

$indexSource = "C:\Users\jairo\.codex\attachments\59f0dbf1-10da-4c11-a115-a64e017f478a\pasted-text.txt"
$appSource = "C:\Users\jairo\.codex\attachments\23813450-17f5-40f9-ae27-1d55e656d669\pasted-text.txt"
$outDir = "D:\Proyectos multi agentes\PartnerHub\tmp\dorian-manual-fix"
$zipPath = "D:\Proyectos multi agentes\PartnerHub\tmp\dorian-manual-fix.zip"

New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$html = Get-Content -Raw -Encoding UTF8 -Path $indexSource

# Los botones Comprar no deben tener href estatico. app.js inyecta la URL real desde CONFIG.distributor.purchaseUrl.
$html = $html -replace 'href="#comprar" target="_blank" rel="noopener noreferrer" class="btn btn-primary product-btn-buy"', 'class="btn btn-primary product-btn-buy" aria-disabled="true"'
$html = $html -replace 'href="#comprar" class="btn btn-primary product-btn-buy"', 'class="btn btn-primary product-btn-buy" aria-disabled="true"'
$html = $html -replace '<a class="btn btn-primary product-btn-buy" id=', '<a class="btn btn-primary product-btn-buy" aria-disabled="true" id='

Set-Content -Path (Join-Path $outDir "index.html") -Value $html -Encoding UTF8

$app = Get-Content -Raw -Encoding UTF8 -Path $appSource

# Evita una tienda de respaldo quemada si config.js no carga.
$app = $app -replace "purchaseUrl:\s*'https://colombia\.ganoexcel\.com/GanoMaster'", "purchaseUrl: ''"

Set-Content -Path (Join-Path $outDir "app.js") -Value $app -Encoding UTF8

$config = @'
// Generated by PartnerHub PH-005B. Do not edit manually.
const CONFIG = {
  "site": {
    "id": "dorian-higuita",
    "domain": "dorianhiguita.pro",
    "title": "DorianWellness — Bienestar y Vitalidad con Gano Excel",
    "appName": "dorian_higuita",
    "ogTitle": "DorianWellness — Bienestar y Vitalidad con Gano Excel",
    "ogDescription": "Descubre como transformar tu dia a dia con cafe, cacao y suplementos enriquecidos con Ganoderma lucidum por DorianWellness.",
    "metaDescription": "Descubre como transformar tu dia a dia con cafe, cacao y suplementos enriquecidos con Ganoderma lucidum por DorianWellness."
  },
  "distributor": {
    "brandName": "DorianWellness",
    "firstName": "Dorian",
    "fullName": "Dorian Higuita",
    "role": "Distribuidor Autorizado · Gano Excel",
    "whatsappNumber": "3132794180",
    "phoneNumber": "3216628760",
    "displayPhone": "3216628760",
    "purchaseUrl": "https://col.ganoexcel.com/dorianwellness",
    "defaultMessage": "Hola Dorian, vengo de tu página web. Me gustaría tener más información sobre el Ganoderma de Gano Excel."
  },
  "hero": {
    "desktop": "https://media.partnerhub.club/clientes/dorian-higuita/producto/v1/hero-desktop-ms7vnbfs.webp",
    "mobile": "https://media.partnerhub.club/clientes/dorian-higuita/producto/v1/hero-mobile-ms7vndsa.webp"
  },
  "mediaBaseUrl": "https://media.partnerhub.club/comunes/producto/v1/"
};

if (typeof window !== "undefined") {
  window.CONFIG = CONFIG;
}
'@

Set-Content -Path (Join-Path $outDir "config.js") -Value $config -Encoding UTF8

if (Test-Path $zipPath) {
  Remove-Item -LiteralPath $zipPath -Force
}

Compress-Archive -Path (Join-Path $outDir "*") -DestinationPath $zipPath

Write-Host "Generated files:"
Get-ChildItem -Path $outDir | Select-Object Name, Length | Format-Table -AutoSize
Write-Host "Zip: $zipPath"
Write-Host "Remaining static buy fallbacks in index.html:"
Select-String -Path (Join-Path $outDir "index.html") -Pattern '#comprar|colombia\.ganoexcel\.com|col\.ganoexcel\.com' | Select-Object LineNumber, Line | Format-Table -AutoSize
Write-Host "Purchase link function in app.js:"
Select-String -Path (Join-Path $outDir "app.js") -Pattern 'function initPurchaseLinks|purchaseUrl|setAttribute\(' | Select-Object -First 20 LineNumber, Line | Format-Table -AutoSize
