import "server-only";

import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { resolve, sep } from "node:path";

import { z } from "zod";

const siteIdSchema = z
  .string()
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "site.id must be a lowercase slug");

const httpsUrlSchema = z.string().url().refine((value) => new URL(value).protocol === "https:", {
  message: "URL must use HTTPS"
});

export const productPageGenerationInputSchema = z.object({
  site: z.object({
    id: siteIdSchema,
    title: z.string().trim().min(1),
    appName: z.string().trim().min(1).optional(),
    ogTitle: z.string().trim().min(1).optional(),
    ogDescription: z.string().trim().min(1).optional(),
    metaDescription: z.string().trim().min(1).optional()
  }),
  distributor: z.object({
    brandName: z.string().trim().min(1),
    firstName: z.string().trim().min(1),
    fullName: z.string().trim().min(1),
    role: z.string().trim().min(1).optional(),
    whatsappNumber: z.string().trim().min(10).max(20),
    phoneNumber: z.string().trim().min(1).optional(),
    displayPhone: z.string().trim().min(1).optional(),
    defaultMessage: z.string().trim().min(1).optional()
  }),
  hero: z.object({
    desktop: httpsUrlSchema,
    mobile: httpsUrlSchema
  }),
  mediaBaseUrl: httpsUrlSchema.optional()
});

export type ProductPageGenerationInput = z.infer<typeof productPageGenerationInputSchema>;

export type ProductPageGenerationResult = {
  siteId: string;
  generatedAt: string;
  outputDirectory: string;
  files: string[];
};

const templateEntries = ["index.html", "styles.css", "app.js", "tipografia"];

function getTemplateDirectory() {
  return process.env.PRODUCT_PAGE_TEMPLATE_DIR ?? "/app/plantillas-de-pagina/producto";
}

function getOutputRoot() {
  return process.env.PRODUCT_PAGE_OUTPUT_DIR ?? "/data/generated-sites";
}

function resolveInsideDirectory(rootDirectory: string, childName: string) {
  const root = resolve(rootDirectory);
  const target = resolve(root, childName);

  if (!target.startsWith(`${root}${sep}`)) {
    throw new Error("Generated package path escaped the configured output directory.");
  }

  return target;
}

function normalizedConfiguration(input: ProductPageGenerationInput) {
  const whatsappNumber = input.distributor.whatsappNumber.replace(/\D/g, "");

  if (whatsappNumber.length < 10 || whatsappNumber.length > 15) {
    throw new Error("distributor.whatsappNumber must contain between 10 and 15 digits.");
  }

  return {
    site: {
      id: input.site.id,
      title: input.site.title,
      appName: input.site.appName ?? input.site.id.replaceAll("-", "_"),
      ogTitle: input.site.ogTitle ?? input.site.title,
      ogDescription: input.site.ogDescription ?? input.site.metaDescription ?? "",
      metaDescription: input.site.metaDescription ?? input.site.ogDescription ?? ""
    },
    distributor: {
      brandName: input.distributor.brandName,
      firstName: input.distributor.firstName,
      fullName: input.distributor.fullName,
      role: input.distributor.role ?? "Distribuidor Autorizado",
      whatsappNumber,
      phoneNumber: input.distributor.phoneNumber ?? whatsappNumber,
      displayPhone: input.distributor.displayPhone ?? input.distributor.phoneNumber ?? whatsappNumber,
      defaultMessage:
        input.distributor.defaultMessage ??
        `Hola ${input.distributor.firstName}, vengo de tu página web y me gustaría recibir más información.`
    },
    hero: input.hero,
    mediaBaseUrl: input.mediaBaseUrl ?? "https://media.partnerhub.club/comunes/producto/v1/"
  };
}

function buildConfigSource(configuration: ReturnType<typeof normalizedConfiguration>) {
  return `// Generated by PartnerHub PH-005B. Do not edit manually.\nconst CONFIG = ${JSON.stringify(configuration, null, 2)};\n\nif (typeof window !== "undefined") {\n  window.CONFIG = CONFIG;\n}\n`;
}

export const productPageGenerationService = {
  async generate(input: ProductPageGenerationInput): Promise<ProductPageGenerationResult> {
    const configuration = normalizedConfiguration(input);
    const templateDirectory = getTemplateDirectory();
    const outputDirectory = resolveInsideDirectory(getOutputRoot(), configuration.site.id);

    await rm(outputDirectory, { recursive: true, force: true });
    await mkdir(outputDirectory, { recursive: true });

    for (const entry of templateEntries) {
      await cp(resolve(templateDirectory, entry), resolve(outputDirectory, entry), {
        recursive: true,
        errorOnExist: false
      });
    }

    const generatedAt = new Date().toISOString();
    const files = [...templateEntries.filter((entry) => entry !== "tipografia"), "config.js", "tipografia/"];

    await writeFile(resolve(outputDirectory, "config.js"), buildConfigSource(configuration), "utf8");
    await writeFile(
      resolve(outputDirectory, "manifest.json"),
      `${JSON.stringify({ siteId: configuration.site.id, generatedAt, files }, null, 2)}\n`,
      "utf8"
    );

    return {
      siteId: configuration.site.id,
      generatedAt,
      outputDirectory,
      files: [...files, "manifest.json"]
    };
  }
};
